version: "3"

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "8080:80"
        depends_on:
            - uni-net
        container_name: uni-net_nginx
    uni-net:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
        depends_on:
            - db
        container_name: uni-net

    db:
        image: mysql:8.0
        restart: always
        volumes:
            - ./tmp/db1:/var/lib/mysql
        environment:
            MYSQL_DATABASE: uni_net
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8101:3306"
        container_name: uni-net_db
